import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show debugPrint;
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

import '../../features/ar/data/glb_bounds.dart';
import '../../features/ar/data/glb_generator.dart';
import '../../features/ar/data/glb_rescaler.dart';
import '../../models/product.dart';

/// Thrown when a product has no resolvable 3D model — either it never got
/// real-world dimensions, or there is nothing to generate from. Callers
/// (the AR viewer screen) fall back to the bundled category model.
class No3dAvailableException implements Exception {
  const No3dAvailableException([this.reason]);

  final String? reason;

  @override
  String toString() => reason == null
      ? 'No3dAvailableException: no 3D model available for this product'
      : 'No3dAvailableException: $reason';
}

/// A product's GLB materialized as a local file, ready for AR placement.
class ResolvedGlb {
  const ResolvedGlb({required this.file, required this.procedural});

  /// Absolute path to the GLB on disk (app documents/`ar_models/`).
  ///
  /// Feed `Uri.file(file.path).toString()` to
  /// `ARNode(type: NodeType.fileSystemAppFolderGLB, …)` — the plugin reads
  /// the file directly. Geometry already spans the product's exact
  /// W×H×D meters (grounded at y = 0), so the node's uniform scale is 1.0.
  final File file;

  /// True when the bytes came from the deterministic built-in generator
  /// (no network, no per-product external asset). False for downloaded /
  /// rescaled AI models.
  final bool procedural;

  @override
  String toString() =>
      'ResolvedGlb(${file.path}, procedural: $procedural)';
}

/// Materializes a [Product]'s 3D model as a local GLB file at TRUE size.
///
/// Priority:
///  1. `ar3d.status == 'ready'` with an http(s) `url` → download the AI
///     model, validate + rescale it to the product's current dimensions
///     (grounded at y = 0), cache it under the AI cache key. Any failure here
///     (offline, bad file, stale URL) falls through to the procedural path.
///  2. complete `dimensions` → generate procedurally (deterministic built-in
///     GLB writer — free, offline), cached under the PROCEDURAL cache key.
///  3. neither → throw [No3dAvailableException].
///
/// Results are cached in the `ar_models/` subfolder of the app documents
/// directory, named `<id>_<stamp>_<dims>.glb`, with cache KEYS SPLIT BY
/// PROVENANCE:
///  - `ai…` stamps (Tripo `generatedAt`, or a URL hash for legacy docs) are
///    used ONLY when AI bytes are actually being cached — an AI download that
///    fails NEVER leaves procedurally generated bytes under an `ai` key
///    (which would label the built-in model with the AI badge on later cache
///    hits);
///  - `p…` stamps (FNV-1a of name + category — renaming/shape-changing a
///    product regenerates) are used for procedurally generated files;
///  - the dims token carries the dimensions label, so a dimension edit
///    rescales/regenerates under a fresh key.
/// The `procedural` flag of a [ResolvedGlb] therefore comes from the KEY the
/// bytes were stored under (the provenance that actually produced them), not
/// from the product's current `ar3d` record — a product whose Tripo download
/// failed resolves procedurally and says so.
/// Sibling files of the same product are pruned after a successful write so
/// the cache holds one model per product.
///
/// Pure async — the caller awaits; no UI is blocked. The class has NO
/// Firebase dependency: only the product object and the local filesystem are
/// touched, so tests run headless with an injected cache directory.
class ModelGlbResolver {
  ModelGlbResolver({
    Future<Directory> Function()? cacheRootProvider,
    http.Client? httpClient,
    Duration downloadTimeout = const Duration(seconds: 60),
  })  : _cacheRootProvider =
            cacheRootProvider ?? getApplicationDocumentsDirectory,
        _http = httpClient ?? http.Client(),
        _downloadTimeout = downloadTimeout;

  /// Folder holding the GLB cache, inside the app documents directory
  /// (`.../app_flutter/ar_models/` on Android — visible to the AR plugin's
  /// `fileSystemAppFolder` node type).
  static const String cacheDirName = 'ar_models';

  final Future<Directory> Function() _cacheRootProvider;
  final http.Client _http;
  final Duration _downloadTimeout;

  /// Releases the underlying HTTP client. Idempotent.
  void dispose() => _http.close();

  Future<ResolvedGlb> resolveProductGlb(Product product) async {
    final dims = product.dimensions;
    final id = product.id.trim();
    if (id.isEmpty) {
      throw const No3dAvailableException(
          'product id is empty — cannot cache a 3D model for it');
    }
    final cacheDir = await _ensureCacheDir();
    final dimsToken = dims == null ? 'nodims' : _sanitize(dims.label);

    // 1) Ready AI model served over the network (Tripo output kept in
    //    Firebase Storage). Only SUCCESSFUL downloads are cached under the
    //    AI key; any failure falls through to the procedural path, which
    //    caches under its OWN key — a procedural file is never written to
    //    (or returned as) the AI cache entry.
    final ar3d = product.ar3d;
    final aiReady =
        ar3d != null && ar3d.status == 'ready' && ar3d.url.startsWith('http');
    if (aiReady) {
      final aiTarget = File('${cacheDir.path}${Platform.pathSeparator}'
          '${_sanitize(id)}_${_aiStamp(ar3d)}_$dimsToken.glb');
      if (aiTarget.existsSync() && aiTarget.lengthSync() > 0) {
        return ResolvedGlb(file: aiTarget, procedural: false);
      }
      try {
        final resp = await _http.get(Uri.parse(ar3d.url))
            .timeout(_downloadTimeout);
        if (resp.statusCode == 200 && resp.bodyBytes.isNotEmpty) {
          final bytes = _prepareDownloaded(resp.bodyBytes, product);
          await _writeAndPrune(cacheDir, id, aiTarget, bytes);
          return ResolvedGlb(file: aiTarget, procedural: false);
        }
        debugPrint('[model-3d] download of ${ar3d.url} returned '
            'HTTP ${resp.statusCode} — falling back to procedural');
      } catch (e) {
        debugPrint('[model-3d] download of ${ar3d.url} failed: $e — '
            'falling back to procedural');
      }
    }

    // 2) Procedural: the deterministic built-in generator needs full dims.
    //    Its own `p` cache key — a cache hit here is unambiguously
    //    procedural (AI bytes never share this key).
    final pTarget = File('${cacheDir.path}${Platform.pathSeparator}'
        '${_sanitize(id)}_p${_fnv1a('${product.name}|${product.category}')}'
        '_$dimsToken.glb');
    if (pTarget.existsSync() && pTarget.lengthSync() > 0) {
      return ResolvedGlb(file: pTarget, procedural: true);
    }
    if (dims != null && dims.isComplete) {
      final bytes = generateFurnitureGlb(
        category: product.category,
        name: product.name,
        widthM: dims.widthM,
        heightM: dims.heightM,
        depthM: dims.depthM,
      );
      await _writeAndPrune(cacheDir, id, pTarget, bytes);
      return ResolvedGlb(file: pTarget, procedural: true);
    }

    // 3) Nothing to work from.
    throw const No3dAvailableException(
        'add real-world dimensions (Width/Height/Depth) to auto-generate '
        'the 3D model');
  }

  /// Validates the downloaded bytes parse as a GLB and rescales them to the
  /// product's dimensions (when complete). Without complete dimensions the
  /// bytes are cached as-is.
  Uint8List _prepareDownloaded(Uint8List raw, Product product) {
    // Throws GlbParseException on garbage — caller falls back to procedural.
    GlbBounds.fromGlbBytes(raw);
    final dims = product.dimensions;
    if (dims == null || !dims.isComplete) return raw;
    return rescaleGlbToDimensions(
      raw,
      targetWidthM: dims.widthM,
      targetHeightM: dims.heightM,
      targetDepthM: dims.depthM,
    );
  }

  /// The `ai…` cache-stamp segment of a ready network model: the Tripo
  /// `generatedAt` epoch (a new AI run replaces the cached download), or a
  /// URL hash for legacy ready docs without a timestamp.
  static String _aiStamp(Ar3dInfo ar3d) {
    final at = ar3d.generatedAt;
    return at != null ? 'ai${at.millisecondsSinceEpoch}' : 'ai_${_fnv1a(ar3d.url)}';
  }

  Future<Directory> _ensureCacheDir() async {
    final root = await _cacheRootProvider();
    final dir = Directory('${root.path}${Platform.pathSeparator}$cacheDirName');
    if (!dir.existsSync()) dir.createSync(recursive: true);
    return dir;
  }

  Future<void> _writeAndPrune(
      Directory cacheDir, String productId, File target, Uint8List bytes) async {
    await target.writeAsBytes(bytes, flush: true);
    // Keep exactly one cached model per product.
    final prefix = '${_sanitize(productId)}_';
    try {
      for (final f in cacheDir.listSync()) {
        if (f is! File) continue;
        final name = f.uri.pathSegments.last;
        if (name.startsWith(prefix) &&
            name.endsWith('.glb') &&
            f.path != target.path) {
          f.deleteSync();
        }
      }
    } catch (e) {
      debugPrint('[model-3d] cache prune failed: $e');
    }
  }

  /// Deletes every cached GLB belonging to [productId]. Best-effort — used
  /// when a product is deleted so its documents-cache model goes too.
  static Future<void> pruneCacheForProduct(String productId) async {
    if (productId.trim().isEmpty) return;
    try {
      final root = await getApplicationDocumentsDirectory();
      final dir =
          Directory('${root.path}${Platform.pathSeparator}$cacheDirName');
      if (!dir.existsSync()) return;
      final prefix = '${_sanitize(productId)}_';
      for (final f in dir.listSync()) {
        if (f is! File) continue;
        final name = f.uri.pathSegments.last;
        if (name.startsWith(prefix) && name.endsWith('.glb')) {
          f.deleteSync();
        }
      }
    } catch (e) {
      debugPrint('[model-3d] cache prune for $productId failed: $e');
    }
  }

  static String _sanitize(String s) =>
      s.replaceAll(RegExp(r'[^a-zA-Z0-9._-]'), '_');

  /// Deterministic FNV-1a (model output must not depend on VM hashing).
  static String _fnv1a(String text) {
    var h = 0x811C9DC5;
    for (final c in text.codeUnits) {
      h = ((h ^ c) * 0x01000193) & 0xFFFFFFFF;
    }
    return h.toRadixString(16);
  }
}
